### ISSUE TITLE
comment on http://microclim.org/APIs

### ISSUE THREAD

**Issue by levyofi** [trenchproject/ebm#13]
Show working examples.

**Comment by lbuckley** [comment]
Add to page:
How to access / install?
Specify R and Phython.
How to retrieve and use “key” and “secret” codes.
Include example use from manuscript.
Specify that one combination of parameters can be requested at a time?
What if variables do not have height or shade levels? Default to NA?

**Comment by lbuckley** [comment]
Also text changes:
# varname should correspond to “Variable” column from table on main page
# interval indicates the time interval over which data should be aggregated

**Comment by ajijohn** [comment]
Added binder and details on usage
